server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
